context:
  version: "1.0.0"

package:
  name: q-kx-log
  version: ${{ version }}

source:
  path: ..
  filter:
    exclude:
      - recipe/**

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/lib/q/mod/kx
    - cp log.q $PREFIX/lib/q/mod/kx/

requirements:
  run:
    - q-kx-printf

tests:
  - script:
    - test -f ${PREFIX}/lib/q/mod/kx/log.q
